// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Local, disposable DB that `migrate dev` resets to validate migrations.
    // MUST point at an empty throwaway database — never one with real data.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
