#!/usr/bin/env node
/**
 * Spins up a disposable PostgreSQL container for the regression test suite and
 * applies the Prisma schema to it. Idempotent: re-running reuses the existing
 * container (and its already-chosen port) instead of clobbering it.
 *
 * - Picks a FREE TCP port automatically (never reuses one that's already bound).
 * - Writes connection details to .env.test (gitignored) — no creds are committed.
 * - The test code itself reads everything from process.env; nothing is hardcoded
 *   there. This file only provisions a throwaway *local* database.
 *
 * Usage:  node scripts/setup-test-db.mjs
 * Teardown: docker rm -f apptracker-test-db
 */
import { execSync } from "node:child_process";
import { createServer } from "node:net";
import { randomBytes } from "node:crypto";
import { writeFileSync, existsSync, readFileSync } from "node:fs";

const CONTAINER = "apptracker-test-db";
const IMAGE = "postgres:16-alpine";
const DB_USER = "test";
const DB_NAME = "apptracker_test";
const ENV_FILE = ".env.test";

function sh(cmd, opts = {}) {
  return execSync(cmd, { stdio: ["ignore", "pipe", "pipe"], encoding: "utf8", ...opts }).trim();
}

function findFreePort(start = 5433, end = 5600) {
  return new Promise((resolve, reject) => {
    const tryPort = (port) => {
      if (port > end) return reject(new Error("No free port found in range"));
      const srv = createServer();
      srv.once("error", () => tryPort(port + 1));
      srv.once("listening", () => srv.close(() => resolve(port)));
      srv.listen(port, "127.0.0.1");
    };
    tryPort(start);
  });
}

function containerState() {
  try {
    const out = sh(`docker ps -a --filter name=^/${CONTAINER}$ --format "{{.State}}"`);
    return out || "absent";
  } catch {
    return "absent";
  }
}

function mappedPort() {
  // e.g. "0.0.0.0:5433" -> 5433
  const out = sh(`docker port ${CONTAINER} 5432/tcp`);
  const m = out.match(/:(\d+)\s*$/m);
  if (!m) throw new Error(`Could not parse mapped port from: ${out}`);
  return Number(m[1]);
}

function envValue(key) {
  if (!existsSync(ENV_FILE)) return null;
  const line = readFileSync(ENV_FILE, "utf8").split("\n").find((l) => l.startsWith(`${key}=`));
  return line ? line.slice(key.length + 1) : null;
}

async function main() {
  // Verify docker daemon is reachable up front with a clear message.
  try {
    sh("docker info");
  } catch {
    console.error("✗ Docker daemon is not running. Start Docker Desktop and re-run.");
    process.exit(1);
  }

  const state = containerState();
  let port;
  // Preserve the password across reruns so .env.test stays valid for a running container.
  let password = envValue("TEST_DB_PASSWORD") || randomBytes(16).toString("hex");

  if (state === "running") {
    port = mappedPort();
    console.log(`• Reusing running container "${CONTAINER}" on port ${port}`);
  } else if (state === "exited" || state === "created") {
    sh(`docker start ${CONTAINER}`);
    port = mappedPort();
    console.log(`• Started existing container "${CONTAINER}" on port ${port}`);
  } else {
    port = await findFreePort();
    console.log(`• Creating container "${CONTAINER}" on free port ${port}`);
    sh(
      `docker run -d --name ${CONTAINER} ` +
        `-e POSTGRES_USER=${DB_USER} -e POSTGRES_PASSWORD=${password} -e POSTGRES_DB=${DB_NAME} ` +
        `-p 127.0.0.1:${port}:5432 ${IMAGE}`
    );
  }

  const databaseUrl = `postgresql://${DB_USER}:${password}@127.0.0.1:${port}/${DB_NAME}`;

  // Wait for Postgres to accept connections.
  process.stdout.write("• Waiting for Postgres to be ready");
  let ready = false;
  for (let i = 0; i < 30; i++) {
    try {
      sh(`docker exec ${CONTAINER} pg_isready -U ${DB_USER} -d ${DB_NAME}`);
      ready = true;
      break;
    } catch {
      process.stdout.write(".");
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
  console.log(ready ? " ready" : " timeout");
  if (!ready) {
    console.error("✗ Postgres did not become ready in time.");
    process.exit(1);
  }

  // A 64-char hex key is required by src/lib/crypto.ts. AUTH_SECRET is a dummy
  // for any module that reads it; the real auth module is mocked in tests.
  const encryptionKey = envValue("ENCRYPTION_KEY") || randomBytes(32).toString("hex");

  writeFileSync(
    ENV_FILE,
    [
      "# Auto-generated by scripts/setup-test-db.mjs — DO NOT COMMIT (gitignored).",
      "# Throwaway local test database. Regenerate with: node scripts/setup-test-db.mjs",
      `TEST_DB_PASSWORD=${password}`,
      `DATABASE_URL=${databaseUrl}`,
      `ENCRYPTION_KEY=${encryptionKey}`,
      "AUTH_SECRET=test-secret-not-used",
      "",
    ].join("\n")
  );
  console.log(`• Wrote ${ENV_FILE}`);

  // Replay the migration files rather than `db push`-ing the schema.
  //
  // `db push` derives DDL from schema.prisma, which cannot express everything
  // the real database has — RateLimitEvent's "exactly one subject" CHECK lives
  // in raw SQL in a migration. Pushing the schema would silently omit it, so
  // tests would run against a laxer database than production and could never
  // catch a violation. Replaying migrations gives the test DB identical DDL.
  //
  // The container may already hold tables from a previous run, with no
  // migration history for `deploy` to reconcile against, so wipe the schema
  // first. Done with plain SQL inside the container rather than
  // `prisma migrate reset` — that command refuses to run unattended, and this
  // is unambiguously scoped to the throwaway container created above (the
  // statement is executed via `docker exec` on ${CONTAINER}, so it cannot
  // reach any other database however DATABASE_URL is set).
  console.log("• Dropping existing test schema…");
  sh(
    `docker exec ${CONTAINER} psql -U ${DB_USER} -d ${DB_NAME} ` +
      `-c "DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;"`
  );

  console.log("• Applying migrations (migrate deploy)…");
  execSync("npx prisma migrate deploy", {
    stdio: "inherit",
    env: { ...process.env, DATABASE_URL: databaseUrl },
  });

  console.log("✓ Test database ready.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
